const topwords = require('./topwords');

test('topwords should return key-value object of the top 20 words with their counts', () => {
    const words = [
        'cat',
        'dog',
        'hamster',
        'rabbit',
        'wolf',
        'deer',
        'elephant',
        'giraffe',
        'rhinoceros',
        'bear',
        'snake',
        'cow',
        'donkey',
        'horse',
        'bird',
        'worm',
        'bee',
        'fish',
        'whale',
        'turtle',
        'fox',
        'otter',
        'mouse',
        'bear',
        'cat',
        'mouse',
        'otter',
        'kangaroo',
        'possum',
        'platypus',
        'wolf',
        'kangaroo',
        'bird',
        'spider',
        'snake',
        'rabbit',
        'wolf',
        'kangaroo',
        'wombat',
        'weasel',
        'bat',
        'fox',
        'snake',
        'chicken',
        'deer',
        'bird',
        'worm',
        'cat',
        'dog',
        'duck',
        'cat',
        'bird',
        'wolf',
        'tiger',
        'lynx',
        'bird',
        'mouse',
        'otter',
        'turtle',
        'fish',
        'horse',
        'cow',
        'sheep',
        'donkey',
        'mule',
        'horse'
    ];

    expect(topwords(words)).toEqual({
        'wolf': 4,
        'cat': 4,
        'dog': 2,
        'bird': 5,
        'kangaroo': 3,
        'horse': 3,
        'mouse': 3,
        'otter': 3,
        'snake': 3,
        'bear': 2,
        'cow': 2,
        'deer': 2,
        'fish': 2,
        'fox': 2,
        'rabbit': 2,
        'turtle': 2,
        'worm': 2,
        'donkey': 2,
        'possum': 1,
        'bee': 1
    });
});
